name: Application Testing
on:
  workflow_call:
jobs:
  application_testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Step 1"
        shell: bash
      - run: echo "Step 2"
        shell: bash