name:  Deploy to Develop
on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
jobs:
  coding_standards_checks:
    uses: ./.github/workflows/coding-standards-checks.yml
  phpstan_static_analysis:
    uses: ./.github/workflows/phpstan-static-analysis.yml
  yaml_lint:
    uses: ./.github/workflows/yaml-lint.yml
  test_site_install:
    uses: ./.github/workflows/test-site-installation.yml
  dry_run_deployment:
    uses: ./.github/workflows/dry-run-deployment.yml
#    secrets:
#      ACQUIA_API_KEY: ${{ secrets.ACQUIA_API_KEY }}
#      ACQUIA_API_SECRET: ${{ secrets.ACQUIA_API_SECRET }}
#      PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
  deploy:
    needs: [coding_standards_checks, phpstan_static_analysis, yaml_lint, test_site_install, dry_run_deployment]
    uses: ./.github/workflows/deploy-code.yml
#    secrets:
#      ACQUIA_API_KEY: ${{ secrets.ACQUIA_API_KEY }}
#      ACQUIA_API_SECRET: ${{ secrets.ACQUIA_API_SECRET }}
#      PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}

# Alternate job example using check for prior workflow results.
#jobs:
#  application_tests:
#    uses: ./.github/workflows/application-tests.yml
#  deploy:
#    runs-on: ubuntu-latest
#    needs: [application_tests]
#    if: always() && contains(needs.*.result, 'success')
#    steps:
#      - run: echo "Step 1"
#        shell: bash
#      - run: echo "Step 2"
#        shell: bash
