name:  Deploy to Stage
on:
  push:
    branches:
      # Will need to changes branches accordingly.
      - 'master'
      - 'main'
jobs:
  security_tests:
    uses: ./.github/workflows/security-checks.yml
  application_tests:
    uses: ./.github/workflows/application-tests.yml
  deploy:
    runs-on: ubuntu-latest
    needs: [application_tests, security_tests]
    if: always() && (needs.application_tests.result == 'success' && needs.application_tests.result == 'success')    
    steps:
      - run: echo "Step 1"
        shell: bash
      - run: echo "Step 2"
        shell: bash
