name:  Run Tests on Code
on:
  push:
    branches:
      - 'main'
      - 'feature/*'
      - 'bugfix/*'
jobs:
  security_tests:
    uses: ./.github/workflows/security-checks.yml
  application_tests:
    uses: ./.github/workflows/application-tests.yml
