name:  Run Tests on Code
on:
  push:
    branches: 
      - 'feature/*'
      - 'bugfix/*'
jobs:
  security_tests:
    uses: ./.github/workflow-templates/security-tests.yml@main
  application_tests:
    uses: ./.github/workflow-templates/application-tests.yml@main
  execute_tests:
    runs-on: ubuntu-latest
    needs: [security_tests, application_tests]
    steps:
      - name: Execute Tests
        shell: bash
        run: echo "Tests completed"
