name: _Validate YAML files (sh)
on:
  workflow_call:
jobs:
  yaml_lint:
    name:  Linting YAML files
    runs-on: ubuntu-latest
    env:
      COMPOSER_MEMORY_LIMIT: -1
    steps:
      - uses: actions/checkout@v4
      - name: Shut down Ubuntu MySQL
        run: sudo service mysql stop
#      - name: Setup DDEV for site install testing
#        uses: ddev/github-action-setup-ddev@v1
#      - name: Validate composer.
#        shell: bash
#        run: ddev composer validate
#      - name: Run composer install
#        shell: bash
#        run: ddev composer install -o
      - name:  Check yaml files to make sure they are valid
#        run: |
#          ddev lint:yaml
        run: |
          echo Success
          exit 0